services:
  postgres:
    image: postgres:18-alpine
    container_name: postgres

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql

    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
        interval: 5s
        timeout: 5s
        retries: 10
    
  fastapi_service:
    build: ./fastapi_service
    container_name: fastapi

    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}

    ports:
      - "8000:8000"

    depends_on:
      - postgres


  go_service:
    build: ./go_service
    container_name: go

    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable
      FASTAPI_URL: http://fastapi:8000

    ports:
      - "8080:8080"

    depends_on:
      - postgres
      - fastapi_service


volumes:
  postgres_data: